# Generated by Django 5.2 on 2025-06-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                max_length=255, null=True, upload_to="posts/images"
            ),
        ),
    ]
