# Generated by Django 5.2 on 2025-05-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img_url",
            field=models.ImageField(null=True, upload_to="posts/images"),
        ),
    ]
