# Generated by Django 5.2 on 2025-06-25 04:15

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_alter_post_img_url_alter_post_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="img_url",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default=django.utils.timezone.now, max_length=255, verbose_name="image"
            ),
            preserve_default=False,
        ),
    ]
